title:            RNAlab
description:      The Laboratory for RNA-Based Lifeforms
disqus_shortname:
reading_time:     false
words_per_minute: 120
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://www.rnalab.ca
enforce_ssl: rnalab.ca
#url: localhost:4000

# Owner/author information
owner:
  name:           A. Babaian
  avatar:         atcg.png
  bio:            "The Laboratory for RNA-Based Lifeforms"
  email:          artem@rRNA.ca
  address:        The Donnelly rm.610
  address2:       160 College St. Toronto.
  address3:       M5S 3E1  
  # Social networking links used in footer. Update and remove as you like.
  twitter:        https://twitter.com/RNA_Life
  scholar:        https://scholar.google.ca/citations?user=FCjKSWcAAAAJ
  github:         ababaian
  focus:          Research focus | Computational Virology & Molecular Genetics
  version:        v1.0.0

  release:        
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Links 
link:
  resume:         https://rRNA.ca
  mogen:          https://moleculargenetics.utoronto.ca/
  donnelly:       https://thedonnellycentre.utoronto.ca/

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Toronto
future:      true  # publish future dated posts --  true, false (default)
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
#  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
#permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - local
